# Generated by Django 4.1.7 on 2023-02-26 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from api.models import ProductMeasurement


def add_product_measurement(apps, schema_editor):
    ProductMeasurement(measurement='UNIDAD', description='Unidad(es)').save()
    ProductMeasurement(measurement='PESO', description='Peso').save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('audit_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product',), name='unique Product'),
        ),
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id_product_measurement', models.AutoField(primary_key=True, serialize=False)),
                ('measurement', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ProductMeasurement',
            constraint=models.UniqueConstraint(fields=('measurement',), name='unique ProductMeasurement'),
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id_supermarket', models.AutoField(primary_key=True, serialize=False)),
                ('supermarket', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('audit_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='supermarket',
            constraint=models.UniqueConstraint(fields=('supermarket', 'location'), name='unique Supermarket'),
        ),
        migrations.CreateModel(
            name='SupermarketProduct',
            fields=[
                ('id_supermarket_product', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('audit_time', models.DateTimeField(auto_now=True)),
                ('last_price', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productmeasurement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supermarket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='SupermarketProduct',
            constraint=models.UniqueConstraint(fields=('supermarket', 'product'), name='unique SupermarketProduct'),
        ),
        migrations.CreateModel(
            name='SupermarketProductRegistry',
            fields=[
                ('id_supermarket_product_registry', models.AutoField(primary_key=True, serialize=False)),
                ('audit_time', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('supermarket_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supermarketproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='SupermarketProductRegistry',
            constraint=models.UniqueConstraint(fields=('supermarket_product', 'price'), name='unique SupermarketProductRegistry'),
        ),
        migrations.RunPython(add_product_measurement),
    ]
